version: '3.9'

services:
  aicryptoadvisor-db:
    image: mongo
    container_name: aicryptoadvisor-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: aicryptoadvisor
      MONGO_INITDB_ROOT_PASSWORD: aicryptoadvisor
    volumes:
      - ./db:/data/db

