version: '3.9'

services:
  mongo:
    image: mongo:6.0
    container_name: aicryptoadvisor
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: aicryptoadvisor
      MONGO_INITDB_ROOT_PASSWORD: aicryptoadvisor
    # volumes:
    #   - mongo_data:/data/db

